name: General
channels:
  - pytorch
  - conda-forge
  - defaults
  - torchvision
dependencies:
  - python=3.10
  - pytorch
  - pandas
  - jupyter
  - matplotlib
  - tensorboard
  - scikit-learn
  - torchmetrics
  - polars
  
